# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(238, 401)
        self.lnIngresarCapital = QtWidgets.QLineEdit(parent=Dialog)
        self.lnIngresarCapital.setGeometry(QtCore.QRect(90, 60, 113, 20))
        self.lnIngresarCapital.setObjectName("lnIngresarCapital")
        self.lnIngresarInteres = QtWidgets.QLineEdit(parent=Dialog)
        self.lnIngresarInteres.setGeometry(QtCore.QRect(90, 90, 113, 20))
        self.lnIngresarInteres.setObjectName("lnIngresarInteres")
        self.lbCapital = QtWidgets.QLabel(parent=Dialog)
        self.lbCapital.setGeometry(QtCore.QRect(20, 60, 47, 13))
        self.lbCapital.setObjectName("lbCapital")
        self.lbInteres = QtWidgets.QLabel(parent=Dialog)
        self.lbInteres.setGeometry(QtCore.QRect(20, 90, 47, 13))
        self.lbInteres.setObjectName("lbInteres")
        self.Titulo = QtWidgets.QLabel(parent=Dialog)
        self.Titulo.setGeometry(QtCore.QRect(30, 30, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Titulo.setFont(font)
        self.Titulo.setScaledContents(True)
        self.Titulo.setObjectName("Titulo")
        self.lbTiempo = QtWidgets.QLabel(parent=Dialog)
        self.lbTiempo.setGeometry(QtCore.QRect(20, 270, 47, 13))
        self.lbTiempo.setObjectName("lbTiempo")
        self.lineIngresarTiempo = QtWidgets.QLineEdit(parent=Dialog)
        self.lineIngresarTiempo.setGeometry(QtCore.QRect(90, 270, 113, 20))
        self.lineIngresarTiempo.setObjectName("lineIngresarTiempo")
        self.sangriaDerecha = QtWidgets.QFrame(parent=Dialog)
        self.sangriaDerecha.setGeometry(QtCore.QRect(220, 30, 20, 361))
        self.sangriaDerecha.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.sangriaDerecha.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.sangriaDerecha.setObjectName("sangriaDerecha")
        self.sangriaDebajo = QtWidgets.QFrame(parent=Dialog)
        self.sangriaDebajo.setGeometry(QtCore.QRect(0, 300, 221, 16))
        self.sangriaDebajo.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.sangriaDebajo.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.sangriaDebajo.setObjectName("sangriaDebajo")
        self.btCalcular = QtWidgets.QPushButton(parent=Dialog)
        self.btCalcular.setGeometry(QtCore.QRect(30, 370, 75, 23))
        self.btCalcular.setObjectName("btCalcular")
        self.btSalir = QtWidgets.QPushButton(parent=Dialog)
        self.btSalir.setGeometry(QtCore.QRect(120, 370, 75, 23))
        self.btSalir.setObjectName("btSalir")
        self.lbMostrarResultado = QtWidgets.QLabel(parent=Dialog)
        self.lbMostrarResultado.setGeometry(QtCore.QRect(10, 320, 201, 31))
        self.lbMostrarResultado.setText("")
        self.lbMostrarResultado.setObjectName("lbMostrarResultado")
        self.lbPeriodos = QtWidgets.QLabel(parent=Dialog)
        self.lbPeriodos.setGeometry(QtCore.QRect(20, 130, 47, 13))
        self.lbPeriodos.setObjectName("lbPeriodos")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbCapital.setText(_translate("Dialog", "Capital"))
        self.lbInteres.setText(_translate("Dialog", "Interes"))
        self.Titulo.setText(_translate("Dialog", "INTERES COMPUESTO"))
        self.lbTiempo.setText(_translate("Dialog", "Tiempo"))
        self.btCalcular.setText(_translate("Dialog", "CALCULAR"))
        self.btSalir.setText(_translate("Dialog", "SALIR"))
        self.lbPeriodos.setText(_translate("Dialog", "Periodos"))
